## Ejercicios - NumPy 1

In [2]:
import numpy as np

In [3]:
# Versión
print(f"numpy=={np.__version__}")

numpy==2.1.1


### Ejercicio 1:
- Crea un vector con 10 elementos pares.

In [3]:
#Las tres opciones a continuación darían el mismo resultado. Son diferentes formas de hacerlo.
lista = []
for i in range(20):
    if i % 2 ==0:
        lista.append(i)
        
np.array(lista)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
lista = []
for i in range(2, 22, 2):
    lista.append(i)
        
np.array(lista)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
array_pares= np.array([i for i in range (2, 22, 2)])
array_pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Ejercicio 2:
- Obten el número de dimensiones y el tamaño del vector anterior.

In [6]:
array_pares.ndim

1

In [7]:
# Número de elementos en total
array_pares.size

10

In [8]:
# Pone la coma porque solo hay un elemento. Número de elementos en cada dimensión
array_pares.shape

(10,)

In [9]:
# Para ver qué tipo de dato es
array_pares.dtype

dtype('int64')

### Ejercicio 3:
- Crea una lista con 5 números pares y otra lista con 5 números impares utilizando **list comprehension** y conviertelos en una matriz de (5, 2) dimensiones.

In [10]:
pares = np.array([i for i in range (2, 12, 2)])
pares

array([ 2,  4,  6,  8, 10])

In [11]:
impares = np.array([i for i in range (1, 11, 2)])
impares



array([1, 3, 5, 7, 9])

In [12]:
#concatenate y reshape
numbers = np.concatenate((pares, impares))
numbers

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [13]:
matriz_5x2 = numbers.reshape(5, 2)
matriz_5x2

array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

In [14]:
# Lo aplana de 2 dimensiones a 1 dimensión:
matriz_5x2.flatten()

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [15]:
np.ravel(matriz_5x2)

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [16]:
np.column_stack((pares, impares))

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9]])

In [17]:
print(pares)
print(np.where(pares > 5))

[ 2  4  6  8 10]
(array([2, 3, 4]),)


In [18]:
indices = np.where(pares > 5) #where devuelve los índices de los elementos que cumplen con las condiciones
pares [indices] # usamos los índices como filtros

array([ 6,  8, 10])

In [19]:
# esto es para pandas
# filtro = df["price"] > 20
# df [filtro]

### Ejercicio 4:
- Obten el tipo de datos de la matriz anterior.

In [20]:
matriz_5x2.dtype

dtype('int64')

### Ejercicio 5:
- Crea una matriz de ceros de dimensión (4, 4) y remplaza los elementos de la diagonal principal por los números 5.

In [6]:
zeros = np.zeros(shape= (4, 4), dtype= "int")

print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Ejercicio 6:
- Utiliza la función _**np.linspace()**_ para crear un vector con 10 elementos entre los números: -5 y 5.

In [8]:
linspace = np.linspace(start = -5, stop= 5, num = 10)
print(linspace)

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


### Ejercicio 7:
- Crea una matriz vacía de tamaño (3, 6) con elementos del tipo flotante.

In [10]:
empty = np.empty(shape = (3, 6), dtype= "float")
print(empty)

[[4.89568518e-310 0.00000000e+000 6.87532745e-310 6.87532633e-310
  6.87533939e-310 6.87532633e-310]
 [6.87532633e-310 6.87532745e-310 6.87532745e-310 4.89568300e-310
  6.87532633e-310 6.87532841e-310]
 [4.89568300e-310 4.89568300e-310 4.89568299e-310 6.87532745e-310
  6.87532789e-310 6.87532745e-310]]


### Ejercicio 8:
- Utiliza la matriz anterior para llenarla con números primos (investiga en internet una función que genere números primos e implementala).

### Ejercicio 9:
- Reemplaza los números de color azul por un 99 utilizando slicing.

$$\Large
\begin{bmatrix}
 1 &  2 &  \color{Blue}{3} &  4 \\
 5 &  \color{Blue}{6} &  7 &  \color{Blue}{8} \\
 \color{Blue}{9} & 10 & 11 & 12 \\
13 & 14 & \color{Blue}{15} & 16
\end{bmatrix}
$$

In [14]:
matriz = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

print(matriz)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Ejercicio 10:
- Obten la primera y tercera fila de la matriz.

### Ejercico 11:
- Obten la tercera columna de la matriz.

### Ejercicio 12:
- Obtener la segunda y tercera columna de la matriz.

### Ejercicio 13:
- Obten una submatriz con los 4 números del centro.

### Ejercicio 14:
- Aplica la función _**np.flatten()**_ a la matriz anterior para obtener un vector.

### Ejercicio 15:
- Aplica el método _**.reshape()**_ al vector anterior para obtener una matriz de (1, 4) dimensiones.

### Ejercicio 16:
- Crea dos matrices de dimensión (4, 4) con números aleatorios y concatenalas verticalmente.

In [3]:
A = np.random.randn(4, 4)
A

array([[ 0.14391762,  0.93618003,  0.36761552,  1.19883841],
       [ 1.47694817,  0.8300519 ,  1.14816715, -0.20907464],
       [ 0.56430887, -0.14684946, -0.80698949, -0.36920058],
       [ 0.93684534, -0.68069332,  2.16057869, -0.46702621]])

In [4]:
B = np.random.randn(4, 4)
B

array([[ 0.51733132, -0.25863208,  0.03886215,  0.13883507],
       [-1.08741352, -0.46680301,  2.18540044,  0.17330966],
       [-0.37196583,  0.0641754 , -0.23152685,  0.26759451],
       [ 1.19518569, -1.60478186,  0.72640736, -0.71197441]])

In [9]:
np.concatenate((A, B), axis=0)

array([[ 0.14391762,  0.93618003,  0.36761552,  1.19883841],
       [ 1.47694817,  0.8300519 ,  1.14816715, -0.20907464],
       [ 0.56430887, -0.14684946, -0.80698949, -0.36920058],
       [ 0.93684534, -0.68069332,  2.16057869, -0.46702621],
       [ 0.51733132, -0.25863208,  0.03886215,  0.13883507],
       [-1.08741352, -0.46680301,  2.18540044,  0.17330966],
       [-0.37196583,  0.0641754 , -0.23152685,  0.26759451],
       [ 1.19518569, -1.60478186,  0.72640736, -0.71197441]])

In [8]:
np.vstack((A, B))

array([[ 0.14391762,  0.93618003,  0.36761552,  1.19883841],
       [ 1.47694817,  0.8300519 ,  1.14816715, -0.20907464],
       [ 0.56430887, -0.14684946, -0.80698949, -0.36920058],
       [ 0.93684534, -0.68069332,  2.16057869, -0.46702621],
       [ 0.51733132, -0.25863208,  0.03886215,  0.13883507],
       [-1.08741352, -0.46680301,  2.18540044,  0.17330966],
       [-0.37196583,  0.0641754 , -0.23152685,  0.26759451],
       [ 1.19518569, -1.60478186,  0.72640736, -0.71197441]])

In [ ]:
################################################################################################################################